# The Docker image that will be used to build your app
image: python:slim

variables:
 # TODO: can this be replaced w/ gitlab variables
 BASE_URL: "/oqapi-jupyter-book"
 HOST: "127.0.0.1"

create-pages:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  # Functions that should be executed before the build script is run
  before_script:
    - pip install uv
    - uv sync
  script:
    - cd src
    - set +o pipefail
    - yes | uv run jupyter book clean
    - uv run jupyter book build --html --ci --keep-host
    - cd ..
    - cp -r src/_build/html/* public
    - touch public/.nojekyll


