name: Build and deploy book

on:
  push:
    branches:
      - main

env:
  BASE_URL: "/oqapi-jupyter-book"
  HOST: "127.0.0.1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install uv
          pip install -r requirements.txt || true

      - name: Build Jupyter Book
        run: |
          cd de
          set +o pipefail
          yes | uv run jupyter book clean
          uv run jupyter book build --ci --html --keep-host

      - name: Prepare GitHub Pages folder
        run: |
          rm -rf public
          mkdir -p public
          cp -r de/_build/html/* public
          touch public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public